export default items = [
  'Bokoblin Horn',
  'Bokoblin Fang',
  'Moblin Fang',
  'Moblin Guts',
  'Lynel Horn',
  'Lynel Hoof',
  'Lynel Guts',
  'Red Chuchu Jelly',
  'Yellow Chuchu Jelly',
  'White Chuchu Jelly',
  'Chuchu Jelly',
  'Keese Eyeball',
  'Bokoblin Guts',
  'Octorok Tentacle',
  'Octorok Eyeball',
  'Molduga Fin',
  'Molduga Guts',
  'Ancient Gear',
  'Ancient Screw',
  'Ancient Spring',
  'Ancient Shaft',
  'Ancient Core',
  'Giant Ancient Core',
  'Lizalfos Horn',
  'Keese Wing',
  'Fire Keese Wing',
  'Electric Keese Wing',
  'Ice Keese Wing',
  'Hinox Toenail',
  'Hinox Tooth',
  'Hinox Guts',
  'Lizalfos Talon',
  'Dinraal\'s Claw',
  'Naydra\'s Claw',
  'Farosh\'s Claw',
  'Shard of Dinraal\'s Horn',
  'Shard of Naydra\'s Horn',
  'Shard of Farosh\'s Horn',
  'Dinraal\'s Scale',
  'Naydra\'s Scale',
  'Farosh\'s Scale',
  'Shard of Dinraal\'s Fang',
  'Shard of Naydra\'s Fang',
  'Shard of Farosh\'s Fang',
  'Octo Balloon',
  'Lizalfos Tail',
  'Red Lizalfos Tail',
  'Icy Lizalfos Tail',
  'Yellow Lizalfos Tail',
  'Moblin Horn',
  'Winterwing Butterfly',
  'Summerwing Butterfly',
  'Sunset Firefly',
  'Fairy',
  'Restless Cricket',
  'Hot-Footed Frog',
  'Tireless Frog',
  'Hearty Lizard',
  'Hightail Lizard',
  'Fireproof Lizard',
  'Thunderwing Butterfly',
  'Smotherwing Butterfly',
  'Cold Darner',
  'Electric Darner',
  'Warm Darner',
  'Rugged Rhino Beetle',
  'Bladed Rhino Beetle',
  'Energetic Rhino Beetle',
  'Diamond',
  'Ruby',
  'Sapphire',
  'Topaz',
  'Opal',
  'Amber',
  'Luminous Stone',
  'Rock Salt',
  'Flint',
  'Star Fragment',
  'Cool Safflina',
  'Warm Safflina',
  'Blue Nightshade',
  'Silent Princess',
  'Electric Safflina',
  'Swift Violet'
]