export default {
  'item_0': "Bokoblin Horn",
  'item_1': "Bokoblin Fang",
  'item_2': "Moblin Fang",
  'item_3': "Moblin Guts",
  'item_4': "Lynel Horn",
  'item_5': "Lynel Hoof",
  'item_6': "Lynel Guts",
  'item_7': "Red Chuchu Jelly",
  'item_8': "Yellow Chuchu Jelly",
  'item_9': "White Chuchu Jelly",
  'item_10': "Chuchu Jelly",
  'item_11': "Keese Eyeball",
  'item_12': "Bokoblin Guts",
  'item_13': "Octorok Tentacle",
  'item_14': "Octorok Eyeball",
  'item_15': "Molduga Fin",
  'item_16': "Molduga Guts",
  'item_17': "Ancient Gear",
  'item_18': "Ancient Screw",
  'item_19': "Ancient Spring",
  'item_20': "Ancient Shaft",
  'item_21': "Ancient Core",
  'item_22': "Giant Ancient Core",
  'item_23': "Lizalfos Horn",
  'item_24': "Keese Wing",
  'item_25': "Fire Keese Wing",
  'item_26': "Electric Keese Wing",
  'item_27': "Ice Keese Wing",
  'item_28': "Hinox Toenail",
  'item_29': "Hinox Tooth",
  'item_30': "Hinox Guts",
  'item_31': "Lizalfos Talon",
  'item_32': "Dinraal's Claw",
  'item_33': "Naydra's Claw",
  'item_34': "Farosh's Claw",
  'item_35': "Shard of Dinraal's Horn",
  'item_36': "Shard of Naydra's Horn",
  'item_37': "Shard of Farosh's Horn",
  'item_38': "Dinraal's Scale",
  'item_39': "Naydra's Scale",
  'item_40': "Farosh's Scale",
  'item_41': "Shard of Dinraal's Fang",
  'item_42': "Shard of Naydra's Fang",
  'item_43': "Shard of Farosh's Fang",
  'item_44': "Octo Balloon",
  'item_45': "Lizalfos Tail",
  'item_46': "Red Lizalfos Tail",
  'item_47': "Icy Lizalfos Tail",
  'item_48': "Yellow Lizalfos Tail",
  'item_49': "Moblin Horn",
  'item_50': "Winterwing Butterfly",
  'item_51': "Summerwing Butterfly",
  'item_52': "Sunset Firefly",
  'item_53': "Fairy",
  'item_54': "Restless Cricket",
  'item_55': "Hot-Footed Frog",
  'item_56': "Tireless Frog",
  'item_57': "Hearty Lizard",
  'item_58': "Hightail Lizard",
  'item_59': "Fireproof Lizard",
  'item_60': "Thunderwing Butterfly",
  'item_61': "Smotherwing Butterfly",
  'item_62': "Cold Darner",
  'item_63': "Electric Darner",
  'item_64': "Warm Darner",
  'item_65': "Rugged Rhino Beetle",
  'item_66': "Bladed Rhino Beetle",
  'item_67': "Energetic Rhino Beetle",
  'item_68': "Diamond",
  'item_69': "Ruby",
  'item_70': "Sapphire",
  'item_71': "Topaz",
  'item_72': "Opal",
  'item_73': "Amber",
  'item_74': "Luminous Stone",
  'item_75': "Rock Salt",
  'item_76': "Flint",
  'item_77': "Star Fragment",
  'item_78': "Cool Safflina",
  'item_79': "Warm Safflina",
  'item_80': "Blue Nightshade",
  'item_81': "Silent Princess",
  'item_82': "Electric Safflina",
  'item_83': "Swift Violet",
  'item_84': "Hyrule Bass",
  'item_85': "Staminoka Bass",
  'item_86': "Hearty Bass",
  'item_87': "Chillfin Trout",
  'item_88': "Voltfin Trout",
  'item_89': "Sizzlefin Trout",
  'item_90': "Stealthfin Trout",
  'item_91': "Hearty Salmon",
  'item_92': "Mighty Carp",
  'item_93': "Armored Carp",
  'item_94': "Sanke Carp",
  'item_95': "Mighty Porgy",
  'item_96': "Armored Porgy",
  'item_97': "Hearty Blueshell Snail",
  'item_98': "Sneaky River Snail",
  'item_99': "Razorclaw Crab",
  'item_100': "Ironshell Crab",
  'item_101': "Bright-Eyed Crab",
  'item_102': "Apple",
  'item_103': "Wildberry",
  'item_104': "Voltfruit",
  'item_105': "Hearty Durian",
  'item_106': "Fleet-Lotus Seeds",
  'item_107': "Hydromelon",
  'item_108': "Palm Fruit",
  'item_109': "Mighty Bananas",
  'item_110': "Stamella Shroom",
  'item_111': "Chillshroom",
  'item_112': "Sunshroom",
  'item_113': "Zapshroom",
  'item_114': "Rushroom",
  'item_115': "Hylian Shroom",
  'item_116': "Hearty Truffle",
  'item_117': "Silent Shroom",
  'item_118': "Razorshroom",
  'item_119': "Ironshroom",
  'item_120': "Big Hearty Truffle",
  'item_121': "Endura Shroom",
  'item_122': "Hearty Radish",
  'item_123': "Big Hearty Radish",
  'item_124': "Mighty Thistle",
  'item_125': "Armoranth",
  'item_126': "Swift Carrot",
  'item_127': "Endura Carrot",
  'item_128': "Spicy Pepper",
  'item_129': "Fortified Pumpkin",
  'item_130': "Acorn",
  'item_131': "Chickaloo Tree Nut",
  'item_132': "Courser Bee Honey",
  'item_133': "Wood",
  'item_134': "Cane Sugar",
  'item_135': "Hylian Rice",
  'item_136': "Tabantha Wheat",
  'item_137': "Goat Butter",
  'item_138': "Fresh Milk",
  'item_139': "Goron Spice",
  'item_140': "Monster Extract"
};