export default [
  { "tag": "item_0", "name": "Bokoblin Horn" },
  { "tag": "item_1", "name": "Bokoblin Fang" },
  { "tag": "item_2", "name": "Moblin Fang" },
  { "tag": "item_3", "name": "Moblin Guts" },
  { "tag": "item_4", "name": "Lynel Horn" },
  { "tag": "item_5", "name": "Lynel Hoof" },
  { "tag": "item_6", "name": "Lynel Guts" },
  { "tag": "item_7", "name": "Red Chuchu Jelly" },
  { "tag": "item_8", "name": "Yellow Chuchu Jelly" },
  { "tag": "item_9", "name": "White Chuchu Jelly" },
  { "tag": "item_10", "name": "Chuchu Jelly" },
  { "tag": "item_11", "name": "Keese Eyeball" },
  { "tag": "item_12", "name": "Bokoblin Guts" },
  { "tag": "item_13", "name": "Octorok Tentacle" },
  { "tag": "item_14", "name": "Octorok Eyeball" },
  { "tag": "item_15", "name": "Molduga Fin" },
  { "tag": "item_16", "name": "Molduga Guts" },
  { "tag": "item_17", "name": "Ancient Gear" },
  { "tag": "item_18", "name": "Ancient Screw" },
  { "tag": "item_19", "name": "Ancient Spring" },
  { "tag": "item_20", "name": "Ancient Shaft" },
  { "tag": "item_21", "name": "Ancient Core" },
  { "tag": "item_22", "name": "Giant Ancient Core" },
  { "tag": "item_23", "name": "Lizalfos Horn" },
  { "tag": "item_24", "name": "Keese Wing" },
  { "tag": "item_25", "name": "Fire Keese Wing" },
  { "tag": "item_26", "name": "Electric Keese Wing" },
  { "tag": "item_27", "name": "Ice Keese Wing" },
  { "tag": "item_28", "name": "Hinox Toenail" },
  { "tag": "item_29", "name": "Hinox Tooth" },
  { "tag": "item_30", "name": "Hinox Guts" },
  { "tag": "item_31", "name": "Lizalfos Talon" },
  { "tag": "item_32", "name": "Dinraal's Claw" },
  { "tag": "item_33", "name": "Naydra's Claw" },
  { "tag": "item_34", "name": "Farosh's Claw" },
  { "tag": "item_35", "name": "Shard of Dinraal's Horn" },
  { "tag": "item_36", "name": "Shard of Naydra's Horn" },
  { "tag": "item_37", "name": "Shard of Farosh's Horn" },
  { "tag": "item_38", "name": "Dinraal's Scale" },
  { "tag": "item_39", "name": "Naydra's Scale" },
  { "tag": "item_40", "name": "Farosh's Scale" },
  { "tag": "item_41", "name": "Shard of Dinraal's Fang" },
  { "tag": "item_42", "name": "Shard of Naydra's Fang" },
  { "tag": "item_43", "name": "Shard of Farosh's Fang" },
  { "tag": "item_44", "name": "Octo Balloon" },
  { "tag": "item_45", "name": "Lizalfos Tail" },
  { "tag": "item_46", "name": "Red Lizalfos Tail" },
  { "tag": "item_47", "name": "Icy Lizalfos Tail" },
  { "tag": "item_48", "name": "Yellow Lizalfos Tail" },
  { "tag": "item_49", "name": "Moblin Horn" },
  { "tag": "item_50", "name": "Winterwing Butterfly" },
  { "tag": "item_51", "name": "Summerwing Butterfly" },
  { "tag": "item_52", "name": "Sunset Firefly" },
  { "tag": "item_53", "name": "Fairy" },
  { "tag": "item_54", "name": "Restless Cricket" },
  { "tag": "item_55", "name": "Hot-Footed Frog" },
  { "tag": "item_56", "name": "Tireless Frog" },
  { "tag": "item_57", "name": "Hearty Lizard" },
  { "tag": "item_58", "name": "Hightail Lizard" },
  { "tag": "item_59", "name": "Fireproof Lizard" },
  { "tag": "item_60", "name": "Thunderwing Butterfly" },
  { "tag": "item_61", "name": "Smotherwing Butterfly" },
  { "tag": "item_62", "name": "Cold Darner" },
  { "tag": "item_63", "name": "Electric Darner" },
  { "tag": "item_64", "name": "Warm Darner" },
  { "tag": "item_65", "name": "Rugged Rhino Beetle" },
  { "tag": "item_66", "name": "Bladed Rhino Beetle" },
  { "tag": "item_67", "name": "Energetic Rhino Beetle" },
  { "tag": "item_68", "name": "Diamond" },
  { "tag": "item_69", "name": "Ruby" },
  { "tag": "item_70", "name": "Sapphire" },
  { "tag": "item_71", "name": "Topaz" },
  { "tag": "item_72", "name": "Opal" },
  { "tag": "item_73", "name": "Amber" },
  { "tag": "item_74", "name": "Luminous Stone" },
  { "tag": "item_75", "name": "Rock Salt" },
  { "tag": "item_76", "name": "Flint" },
  { "tag": "item_77", "name": "Star Fragment" },
  { "tag": "item_78", "name": "Cool Safflina" },
  { "tag": "item_79", "name": "Warm Safflina" },
  { "tag": "item_80", "name": "Blue Nightshade" },
  { "tag": "item_81", "name": "Silent Princess" },
  { "tag": "item_82", "name": "Electric Safflina" },
  { "tag": "item_83", "name": "Swift Violet" },
  { "tag": "item_84", "name": "Hyrule Bass" },
  { "tag": "item_85", "name": "Staminoka Bass" },
  { "tag": "item_86", "name": "Hearty Bass" },
  { "tag": "item_87", "name": "Chillfin Trout" },
  { "tag": "item_88", "name": "Voltfin Trout" },
  { "tag": "item_89", "name": "Sizzlefin Trout" },
  { "tag": "item_90", "name": "Stealthfin Trout" },
  { "tag": "item_91", "name": "Hearty Salmon" },
  { "tag": "item_92", "name": "Mighty Carp" },
  { "tag": "item_93", "name": "Armored Carp" },
  { "tag": "item_94", "name": "Sanke Carp" },
  { "tag": "item_95", "name": "Mighty Porgy" },
  { "tag": "item_96", "name": "Armored Porgy" },
  { "tag": "item_97", "name": "Hearty Blueshell Snail" },
  { "tag": "item_98", "name": "Sneaky River Snail" },
  { "tag": "item_99", "name": "Razorclaw Crab" },
  { "tag": "item_100", "name": "Ironshell Crab" },
  { "tag": "item_101", "name": "Bright-Eyed Crab" },
  { "tag": "item_102", "name": "Apple" },
  { "tag": "item_103", "name": "Wildberry" },
  { "tag": "item_104", "name": "Voltfruit" },
  { "tag": "item_105", "name": "Hearty Durian" },
  { "tag": "item_106", "name": "Fleet-Lotus Seeds" },
  { "tag": "item_107", "name": "Hydromelon" },
  { "tag": "item_108", "name": "Palm Fruit" },
  { "tag": "item_109", "name": "Mighty Bananas" },
  { "tag": "item_110", "name": "Stamella Shroom" },
  { "tag": "item_111", "name": "Chillshroom" },
  { "tag": "item_112", "name": "Sunshroom" },
  { "tag": "item_113", "name": "Zapshroom" },
  { "tag": "item_114", "name": "Rushroom" },
  { "tag": "item_115", "name": "Hylian Shroom" },
  { "tag": "item_116", "name": "Hearty Truffle" },
  { "tag": "item_117", "name": "Silent Shroom" },
  { "tag": "item_118", "name": "Razorshroom" },
  { "tag": "item_119", "name": "Ironshroom" },
  { "tag": "item_120", "name": "Big Hearty Truffle" },
  { "tag": "item_121", "name": "Endura Shroom" },
  { "tag": "item_122", "name": "Hearty Radish" },
  { "tag": "item_123", "name": "Big Hearty Radish" },
  { "tag": "item_124", "name": "Mighty Thistle" },
  { "tag": "item_125", "name": "Armoranth" },
  { "tag": "item_126", "name": "Swift Carrot" },
  { "tag": "item_127", "name": "Endura Carrot" },
  { "tag": "item_128", "name": "Spicy Pepper" },
  { "tag": "item_129", "name": "Fortified Pumpkin" },
  { "tag": "item_130", "name": "Acorn" },
  { "tag": "item_131", "name": "Chickaloo Tree Nut" },
  { "tag": "item_132", "name": "Courser Bee Honey" },
  { "tag": "item_133", "name": "Wood" },
  { "tag": "item_134", "name": "Cane Sugar" },
  { "tag": "item_135", "name": "Hylian Rice" },
  { "tag": "item_136", "name": "Tabantha Wheat" },
  { "tag": "item_137", "name": "Goat Butter" },
  { "tag": "item_138", "name": "Fresh Milk" },
  { "tag": "item_139", "name": "Goron Spice" },
  { "tag": "item_140", "name": "Monster Extract" }
];